### ISSUE TITLE
JDBC Connectivity Issue to MySQL and Error Logging

### ISSUE THREAD

**Issue by zubairov** [elasticio/jdbc-component#13] opened 2019-05-10 09:19 UTC
@benburch commented on [Fri May 10 2019](https://github.com/elasticio/projects/issues/201)

When trying to run a query against a MySQL database we got an error.

1) Error message - no information, therefore impossible to debug:
`Error: java.lang.ArrayIndexOutOfBoundsException: 1 at io.elastic.jdbc.QueryColumnNamesProvider.getColumns(QueryColumnNamesProvider.java:56) at io.elastic.jdbc.QueryColumnNamesProvider.getMetaModel(QueryColumnNamesProvider.java:36)`

2) The basic queries fail, and the trigger "lookup by primary key"

This was done using a public free MySQL service: 
temp DB:
`Username: V2OvNOFZE6
Password: JyfZRZWAyZ
Database Name: V2OvNOFZE6
Server: remotemysql.com
Port: 3306`

Thread from support here: [SLACK](https://elasticio.slack.com/archives/C6G1E4WB1/p1556611789007800)

Whether the error is in the DB config or somewhere else, the fact is that the logging in the component made it impossible to determine the cause.

**Comment by vdidushko** [comment] 2019-05-10 10:34
When checking Select option and executing next query:
SELECT * FROM customer WHERE Customer_ID = @Request.CustomerDetail.Customer_ID:bigint

It gives 
Error!
java.sql.SQLException: No value specified for parameter 1

Full console log is next:

```
Starting your Docker container ...

[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'

Starting application in apprunner...

Starting slug download ...

Successfully downloaded and extracted slug file

INFO  i.e.s.i.ApiClientImpl T: - Retrieving step data for user task-5cd5526376bda6b0b1167451 at: https://api.elastic.io/v1/tasks/5cd5526376bda6b0b1167451/steps/step_1

INFO  i.e.s.i.HttpUtils T: - Sending GET request to https://api.elastic.io/v1/tasks/5cd5526376bda6b0b1167451/steps/step_1

java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 1
	at io.elastic.jdbc.triggers.SelectTrigger.execute(SelectTrigger.java:95)
	at io.elastic.sailor.impl.MessageProcessorImpl.processMessage(MessageProcessorImpl.java:68)
	at io.elastic.sailor.impl.MessageConsumer.handleDelivery(MessageConsumer.java:68)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: No value specified for parameter 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1036)
	at io.elastic.jdbc.QueryBuilders.Query.executeSelectTrigger(Query.java:119)
	at io.elastic.jdbc.triggers.SelectTrigger.execute(SelectTrigger.java:79)
	... 7 more

INFO  i.e.s.i.HttpUtils T: - Got 200 response

INFO  i.e.s.i.HttpUtils T: - Successfully consumed response entity

INFO  i.e.s.ComponentDescriptorResolver T: - Component descriptor from classpath: /component.json

INFO  i.e.s.Sailor T: - Connecting to AMQP

INFO  i.e.s.i.AmqpServiceImpl T: - Connected to AMQP

INFO  i.e.s.i.AmqpServiceImpl T: - Opened publish channel

INFO  i.e.s.Sailor T: - Module to be executed: selectTrigger

INFO  i.e.s.Sailor T: - Component id to be executed: 55ffca6ecc04c20600000001

INFO  i.e.s.i.AmqpServiceImpl T: - Opened subscribe channel

INFO  i.e.s.Sailor T: - Processing flow step: step_1

INFO  i.e.s.i.ModuleBuilderImpl T: - Module Java class to be instantiated: io.elastic.jdbc.triggers.SelectTrigger

INFO  i.e.s.i.ModuleBuilderImpl T: - Instantiating component io.elastic.jdbc.triggers.SelectTrigger

INFO  i.e.s.Sailor T: - Initializing module for execution

INFO  i.e.s.Sailor T: - Subscribing to queues

INFO  i.e.s.Sailor T: - Sailor started

INFO  i.e.s.i.AmqpServiceImpl T: - Subscribed consumer amq.ctag-KhXCzb4W06q1lHDg5kFxLA. Waiting for messages to arrive ...

INFO  i.e.s.i.MessageConsumer T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Consumer amq.ctag-KhXCzb4W06q1lHDg5kFxLA received message: deliveryTag=1, messageId=bf8dfe97-852e-4ebc-87f5-73cfd9a34431, parentMessageId=unknown, traceId=92b91aed-23e1-4d75-880f-ff11feb1c0f0

INFO  i.e.s.i.CryptoServiceImpl T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Parsing message JSON

INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - About to execute select trigger

INFO  i.e.j.Utils T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Connecting to jdbc:mysql://remotemysql.com:3306/V2OvNOFZE6

**Fri May 10 10:28:59 GMT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.**

INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - EIO_LAST_POLL = 2019-05-10 00:00:00.1

INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Executing select trigger

INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - There is an empty value for Start Polling From at the config and snapshot. So, we set Current Date = 2019-05-10 00:00:00.000

INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - SQL QUERY SELECT * FROM customer WHERE Customer_ID = @Request.CustomerDetail.Customer_ID:bigint :

**INFO  i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - SQL Query: SELECT * FROM customer WHERE Customer_ID = ?.CustomerDetail.Customer_ID:bigint**

ERROR i.e.j.t.SelectTrigger T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Failed to make request

ERROR i.e.s.i.MessageProcessorImpl T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Component execution failed

at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:100)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at io.elastic.jdbc.triggers.SelectTrigger.execute(SelectTrigger.java:95)

at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)

at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)

at io.elastic.sailor.impl.MessageConsumer.handleDelivery(MessageConsumer.java:68)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:127)

at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1036)

at io.elastic.jdbc.triggers.SelectTrigger.execute(SelectTrigger.java:79)

... 7 common frames omitted

**java.lang.RuntimeException: java.sql.SQLException: No value specified for parameter 1**

at io.elastic.sailor.impl.MessageProcessorImpl.processMessage(MessageProcessorImpl.java:68)

at java.lang.Thread.run(Thread.java:748)

Caused by: java.sql.SQLException: No value specified for parameter 1

at io.elastic.jdbc.QueryBuilders.Query.executeSelectTrigger(Query.java:119)

INFO  i.e.s.i.AmqpServiceImpl T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Message headers: {compId=55ffca6ecc04c20600000001, function=selectTrigger, stepId=step_1, start=1557484140130, parentMessageId=bf8dfe97-852e-4ebc-87f5-73cfd9a34431, x-eio-meta-trace-id=92b91aed-23e1-4d75-880f-ff11feb1c0f0, messageId=3c88c462-d2a4-430d-a707-37bf52d24a20, userId=5c92214d7f54180010c96266, taskId=5cd5526376bda6b0b1167451, execId=bca54ad0020b40abbbcb13af7b5dc5fd}

INFO  i.e.s.i.AmqpServiceImpl T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Pushing to exchange=58dcfe0f52f01e0019e7484e_org, routingKey=58dcfe0f52f01e0019e7484e.5cd5526376bda6b0b1167451/debug.step_1.error_debug

INFO  i.e.s.i.MessageConsumer T: - Execution stats: ExecutionStats{dataCount=0, errorCount=1, reboundCount=0}

INFO  i.e.s.i.MessageConsumer T: - Reject received messages 1

INFO  i.e.s.i.AmqpServiceImpl T:92b91aed-23e1-4d75-880f-ff11feb1c0f0 - Successfully published data to 58dcfe0f52f01e0019e7484e_org

```

**Comment by stas-fomenko** [comment] 2019-05-10 11:13
possible **Expected Result** is to emit an user friendly error for invalid field name (`@Request.CustomerDetail.Customer_ID:bigint`) in query: `SELECT * FROM customer WHERE Customer_ID = @Request.CustomerDetail.Customer_ID:bigint`

**Comment by benburch** [comment] 2019-05-10 12:41
@stas-fomenko I think we also tried "SELECT * FROM customer" and that failed. 

Better errors would help.

Note the documentation also explains poorly how this fieldname "@Request.CustomerDetail.Customer_ID:bigint"  should be constructed? We tried other options and values to try to get it to work. 

The fact that it is not JSONata like the rest of the platform is also confusing. @zubairov perhaps there should be standardisation here?

**Comment by vdidushko** [comment] 2019-05-10 13:43
I was able to generate a sample with simple query SELECT * FROM customer

It gives next sample:
{
  "Zip": "W12 7RJ",
  "Customer_Name": "Hogwash Towers Ltd.",
  "Customer_ID": 8
}

However, if executing something like SELECT * FROM customer WHERE customer_id = '2'

Gives execution timeout error message

**Comment by stas-fomenko** [comment] 2019-05-10 14:34
Query `SELECT * FROM customer WHERE customer_id = '2'` executed successfully on our test db: MySQL `8.0.11`
DB version that we have issue with is `8.0.13-4`
so, probably issue is related with DB version

**Comment by zubairov** [comment] 2019-05-13 09:56
@stas-fomenko can you reproduce the issue that @vdidushko described? I don't think it's reasonable to expect that all our customers would have the version of MySQL we expect up to the minor version number?

**Comment by stas-fomenko** [comment] 2019-05-13 10:03
@zubairov bug was reproduced on MySQL 8.0.13-4, but was not on MySQL  8.0.11

**Comment by zubairov** [comment] 2019-05-13 10:09
ok, cool, can we fix it?

**Comment by stas-fomenko** [comment] 2019-05-13 10:32
@zubairov I can not give you an answer right now, it should be investigated first

**Comment by shulkaolka** [comment] 2019-06-07 12:41
1. Query ```SELECT * FROM customer WHERE Customer_ID = @Request.CustomerDetail.Customer_ID:bigint``` is invalid, because  `Request.CustomerDetail.Customer_ID` should be the name of the field in metadata and shouldn't contain the `.` symbol. So from the component side, it should be implemented:
 - emit a user-friendly error for the invalid field name;
 - add limitation about using `.` symbol to readme
2. https://github.com/elasticio/jdbc-component/issues/13#issuecomment-491310764
I tried to reproduce one more time - this case is working for both versions: MySQL 8.0.13-4 and MySQL 8.0.11, so nothing to fix.

**Comment by shulkaolka** [comment] 2019-06-11 13:31
**DoD**

**Component development prerequisites:**

- [x] Development team has all needed requirements
- [x] Access to the needed service with all needed permissions is granted
- [x] No open tasks that could block Component development process
- [x] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [x] Component architecture should be discussed and approved before start coding
- [x] New component GIT repo preconditions:
  - repo type (private/public)
  - license type
- [ ] Component deployment preconditions:
  - Where to deploy (app.elastic.io etc..)
  - Component's access level on each installation that component must be deployed on

**Development:**

- [x] Code is written and formatted in accordance with the Styling guide
- [x] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [x] Component logs do not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [x] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [x] Documentation (README.md file in the Github) is 100% ready
- [ ] Changelogs (CHANGELOG.md) are created/updated
- [ ] Component's version is updated in package.json according to Semantic Versioning 2.0.0
- [ ] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Required Environment Variables are set
  - Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated

**Closed** 2019-06-25 12:01 UTC
Labels: bug
